"""
Project-owned prototype answer sheets: the alignment marker, a printable
blank sheet, and filled-in sheets for testing.

Everything is drawn from a template's own layout file, so the artwork and
the positions OMRChecker reads can never disagree, and it is generated by
code (no photographs, no upstream or community images). The same inputs
always give the same picture.

This module needs OpenCV and NumPy, which only the OMR tooling and tests
use; the web application never imports it.

Layout of a marked sheet (design scale, pixels):

    +--------------------------------------------+
    |  (M)                                  (M)  |   M = alignment marker,
    |     page area: the template's              |       centred `margin`
    |     coordinates start at the top-left      |       pixels in from
    |     marker centre                          |       the sheet edge
    |  (M)                                  (M)  |
    +--------------------------------------------+

OMRChecker finds the four markers, warps the quadrilateral between their
centres to a rectangle, and the template's coordinates are measured there.
"""

import json

import cv2
import numpy as np

from .template import OMRTemplate, expand_labels

BACKGROUND = 245
OUTLINE = 150
MARK_DARK = 40
BUBBLE_RADIUS = 12
MARK_RADIUS = 11
MARKER_SIZE = 64

_FIELD_TYPES = {
    "QTYPE_INT": ("0123456789", "vertical"),
    "QTYPE_MCQ4": ("ABCD", "horizontal"),
}


def marker_image(size: int = MARKER_SIZE) -> np.ndarray:
    """The alignment marker: a black square with a white ring and a black core."""
    image = np.zeros((size, size), np.uint8)
    cv2.rectangle(image, (int(size * 0.2), int(size * 0.2)),
                  (int(size * 0.8) - 1, int(size * 0.8) - 1), 255, -1)
    cv2.rectangle(image, (int(size * 0.38), int(size * 0.38)),
                  (int(size * 0.62) - 1, int(size * 0.62) - 1), 0, -1)
    return image


def _bubble_positions(template: OMRTemplate):
    """{label: {value: (x, y)}} (top-left of each bubble box) from the layout."""
    layout = json.loads(template.layout_path.read_text())
    positions = {}

    for block in layout["fieldBlocks"].values():
        values, direction = _FIELD_TYPES[block["fieldType"]]
        ox, oy = block["origin"]
        for i, label in enumerate(expand_labels(block["fieldLabels"])):
            positions[label] = {}
            for j, value in enumerate(values):
                if direction == "horizontal":
                    xy = (ox + j * block["bubblesGap"], oy + i * block["labelsGap"])
                else:
                    xy = (ox + i * block["labelsGap"], oy + j * block["bubblesGap"])
                positions[label][value] = xy

    return layout, positions


def render_sheet(
    template: OMRTemplate,
    roll: str,
    answers: dict[int, str] | None = None,
    *,
    labels: bool = False,
    seed: int = 0,
    shading: bool = True,
    noise_sigma: float = 5.0,
) -> np.ndarray:
    """
    A grayscale picture of a sheet.

    `roll` has one digit per roll column ("" for a blank sheet). `answers`
    maps question number to "" (blank), "A".."D", or several letters for
    a multi-mark. `labels` adds the printed numbers and letters (outside
    the bubbles) that a real sheet would have; `shading` and
    `noise_sigma` add mild uneven lighting and sensor noise.
    """

    layout, positions = _bubble_positions(template)
    page_w, page_h = layout["pageDimensions"]
    box = layout["bubbleDimensions"][0]
    margin = template.sheet_margin
    width, height = page_w + 2 * margin, page_h + 2 * margin
    image = np.full((height, width), BACKGROUND, np.uint8)

    def centre(xy):
        return int(margin + xy[0] + box / 2), int(margin + xy[1] + box / 2)

    if template.marker_file:
        marker = cv2.imread(str(template.directory / template.marker_file), cv2.IMREAD_GRAYSCALE)
        half = marker.shape[0] // 2
        for cx, cy in ((margin, margin), (margin + page_w, margin),
                       (margin, margin + page_h), (margin + page_w, margin + page_h)):
            image[cy - half:cy - half + marker.shape[0], cx - half:cx - half + marker.shape[1]] = marker

    for values in positions.values():
        for xy in values.values():
            cv2.circle(image, centre(xy), BUBBLE_RADIUS, OUTLINE, 2)

    if labels:
        _draw_labels(image, template, layout, margin)

    def mark(label, value):
        cv2.circle(image, centre(positions[label][value]), MARK_RADIUS, MARK_DARK, -1)

    roll_labels = expand_labels(layout["customLabels"][template.roll_field])
    for label, digit in zip(roll_labels, roll):
        mark(label, digit)

    for number, letters in (answers or {}).items():
        for letter in letters:
            mark(template.column_for(number), letter)

    if shading or noise_sigma:
        rng = np.random.default_rng(seed)
        out = image.astype(np.float32)
        if shading:
            out *= np.tile(np.linspace(0.9, 1.0, width, dtype=np.float32), (height, 1))
        if noise_sigma:
            out += rng.normal(0, noise_sigma, image.shape)
        image = np.clip(out, 0, 255).astype(np.uint8)

    return image


def _draw_labels(image, template, layout, margin) -> None:
    """Question numbers, option letters and roll digits, outside the bubbles."""
    font = cv2.FONT_HERSHEY_SIMPLEX
    box = layout["bubbleDimensions"][0]

    for block in layout["fieldBlocks"].values():
        values, direction = _FIELD_TYPES[block["fieldType"]]
        ox, oy = block["origin"]
        labels = expand_labels(block["fieldLabels"])
        gap_b, gap_l = block["bubblesGap"], block["labelsGap"]

        if direction == "horizontal":
            for j, value in enumerate(values):                       # A B C D above
                cv2.putText(image, value, (margin + ox + j * gap_b + box // 4, margin + oy - 14),
                            font, 0.5, 90, 1, cv2.LINE_AA)
            for i, label in enumerate(labels):                       # question numbers left
                cv2.putText(image, label.lstrip("q"), (margin + ox - 42, margin + oy + i * gap_l + box - 8),
                            font, 0.45, 90, 1, cv2.LINE_AA)
        else:
            for j, value in enumerate(values):                       # digits left of rows
                cv2.putText(image, value, (margin + ox - 26, margin + oy + j * gap_b + box - 8),
                            font, 0.45, 90, 1, cv2.LINE_AA)
            cv2.putText(image, "ROLL NUMBER", (margin + ox, margin + oy - 18),
                        font, 0.5, 90, 1, cv2.LINE_AA)


def to_png(image: np.ndarray) -> bytes:
    ok, encoded = cv2.imencode(".png", image)
    if not ok:
        raise ValueError("could not encode the image")
    return encoded.tobytes()
